version: '3.7'

services:
  db:
    image: postgres:12.5-alpine
    restart: always
    container_name: le_tech_storage
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=le_tech
      - POSTGRES_DB=le_tech
      - POSTGRES_PASSWORD=ddk0Re!!wIjpGAPzfa.XrQ

volumes:
  postgres_data:
