server:
  port: 8080
  servlet:
    context-path: /
logging:
  level:
    org:
      springframework: ERROR
spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    password: ddk0Re!!wIjpGAPzfa.XrQ
    platform: postgres
    url: jdbc:postgresql://localhost:5432/le_tech
    username: le_tech
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-source: metadata
              create-target: ./src/main/resources/db/migration/create.sql

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/baeldung
          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs

---
spring:
  profiles: compose
  datasource:
    password: ddk0Re!!wIjpGAPzfa.XrQ
    platform: postgres
    url: jdbc:postgresql://localhost:5432/le_tech
    username: le_tech
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-source: metadata
              create-target: ./src/main/resources/db/migration/create.sql
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/baeldung
          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs

